production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "high_priority"
      threads: 5
      processes: 3
      polling_interval: 0.1
    - queues: "default"
      threads: 3
      processes: 5
      polling_interval: 0.5
    - queues: "low_priority"
      threads: 2
      processes: 2
      polling_interval: 1

development:
  dispatchers:
    - polling_interval: 1
      batch_size: 100
  workers:
    - queues: "*"
      threads: 3
      processes: 2
      polling_interval: 1

test:
  dispatchers:
    - polling_interval: 1
      batch_size: 100
  workers:
    - queues: "*"
      threads: 3
      processes: 2
      polling_interval: 1
